name: heat_iq_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '^3.7.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
